#!/bin/sh
now=$(date +"%r")
COLS=$(tput cols)
HEXAGRAMS=("䷀" "䷁" "䷂" "䷃" "䷄" "䷅" "䷆" "䷇" "䷈" "䷉" "䷊" "䷋" "䷌" "䷍" "䷎" "䷏" "䷐" "䷑" "䷒" "䷓" "䷔" "䷕" "䷖" "䷗" "䷘" "䷙" "䷚" "䷛" "䷜" "䷝" "䷞" "䷟" "䷠" "䷡" "䷢" "䷣" "䷤" "䷥" "䷦" "䷧" "䷨" "䷩" "䷪" "䷫" "䷬" "䷭" "䷮" "䷯" "䷰" "䷱" "䷲" "䷳" "䷴" "䷵" "䷶" "䷷" "䷸" "䷹" "䷺" "䷻" "䷼" "䷽" "䷾" "䷿")
LINE=""
for number in $(seq 1 $COLS)
do
  RAND=$(jot -r 1 0 63)
  LINE=$LINE${HEXAGRAMS[$RAND]}
done

TIMELINE=""
HALFCOLS=$(expr $COLS / 2 - 7)
for number in $(seq 1 $HALFCOLS)
do
  RAND=$(jot -r 1 0 63)
  TIMELINE=$TIMELINE${HEXAGRAMS[$RAND]}
done

#-------------------------

clear
echo "$TIMELINE $now $TIMELINE"
git --no-pager branch
echo $LINE
echo "\033[0;32m$(git log -1 --pretty='format:%Cgreen%h | %an | %s%+' HEAD)"
echo "\033[0m$(git log -2 --pretty='format:%Cgreen%h | %an | %s%+' HEAD^^^..HEAD^)"
echo $LINE
git status -s
