#!/bin/sh
# requires fswatch and xargs
if [[ $# -gt 0 ]]; then
  gitsup
  fswatch -0 -o -n -e "index.lock" $* | xargs -0 -n1 gitsup
else
  gitsup
  fswatch -0 -o -n -e "index.lock" . | xargs -0 -n1 gitsup
fi
